repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.9
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        name: MyPy
        args: ["--config-file", "pyproject.toml"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: ^.*\.(py|c|h|md|rst|yml)$

exclude: ^src/core/relationaldb/migration_alembic/migrations/.*
